// ============================================
// MAGIC ITEMS DATABASE - M
// ============================================
// DMG and other sourcebook magic items starting with M

const magicItemsM = {
    'mace-of-disruption': {
        name: 'Mace of Disruption',
        type: 'weapon',
        weaponType: 'simple',
        subtype: 'mace',
        rarity: 'rare',
        weight: 4,
        cost: '8,000 gp',
        costValue: 800000,
        attunement: 'any',
        damage: '1d6',
        damageType: 'bludgeoning',
        properties: ['extra radiant damage vs undead/fiends'],
        description: 'When you hit a fiend or an undead with this magic weapon, that creature takes an extra 2d6 radiant damage. If the target has 25 hit points or fewer after taking this damage, it must succeed on a DC 15 Wisdom saving throw or be destroyed. On a successful save, the creature becomes frightened of you until the end of your next turn. While you hold this weapon, it sheds bright light in a 20-foot radius and dim light for an additional 20 feet.',
        source: 'DMG'
    },
    'mace-of-smiting': {
        name: 'Mace of Smiting',
        type: 'weapon',
        weaponType: 'simple',
        subtype: 'mace',
        rarity: 'rare',
        weight: 4,
        cost: '7,000 gp',
        costValue: 700000,
        attunement: 'none',
        damage: '1d6+3',
        damageType: 'bludgeoning',
        properties: ['+3 weapon', 'extra damage vs constructs'],
        description: 'You gain a +3 bonus to attack and damage rolls made with this magic weapon. When you roll a 20 on an attack roll made with this weapon, the target takes an extra 2d6 bludgeoning damage, or 4d6 bludgeoning damage if it\'s a construct. If a construct has 25 hit points or fewer after taking this damage, it is destroyed.',
        source: 'DMG'
    },
    'mace-of-terror': {
        name: 'Mace of Terror',
        type: 'weapon',
        weaponType: 'simple',
        subtype: 'mace',
        rarity: 'rare',
        weight: 4,
        cost: '8,000 gp',
        costValue: 800000,
        attunement: 'any',
        damage: '1d6',
        damageType: 'bludgeoning',
        charges: 3,
        recharge: '1d3 at dawn',
        description: 'This magic weapon has 3 charges. While holding it, you can use an action and expend 1 charge to release a wave of terror. Each creature of your choice in a 30-foot radius extending from you must succeed on a DC 15 Wisdom saving throw or become frightened of you for 1 minute. While it is frightened in this way, a creature must spend its turns trying to move as far away from you as it can, and it can\'t willingly move to a space within 30 feet of you. It also can\'t take reactions. For its action, it can use only the Dash action or try to escape from an effect that prevents it from moving. If it has nowhere it can move, the creature can use the Dodge action. At the end of each of its turns, a creature can repeat the saving throw, ending the effect on itself on a success.',
        source: 'DMG'
    },
    'mantle-of-spell-resistance': {
        name: 'Mantle of Spell Resistance',
        type: 'wondrous-item',
        rarity: 'rare',
        weight: 1,
        cost: '12,000 gp',
        costValue: 1200000,
        attunement: 'any',
        description: 'You have advantage on saving throws against spells while you wear this cloak.',
        source: 'DMG'
    },
    'manual-of-bodily-health': {
        name: 'Manual of Bodily Health',
        type: 'wondrous-item',
        rarity: 'very-rare',
        weight: 5,
        cost: '50,000 gp',
        costValue: 5000000,
        attunement: 'none',
        consumable: true,
        description: 'This book contains health and diet tips, and its words are charged with magic. If you spend 48 hours over a period of 6 days or fewer studying the book\'s contents and practicing its guidelines, your Constitution score increases by 2, as does your maximum for that score. The manual then loses its magic, but regains it in a century.',
        source: 'DMG'
    },
    'manual-of-gainful-exercise': {
        name: 'Manual of Gainful Exercise',
        type: 'wondrous-item',
        rarity: 'very-rare',
        weight: 5,
        cost: '50,000 gp',
        costValue: 5000000,
        attunement: 'none',
        consumable: true,
        description: 'This book describes fitness exercises, and its words are charged with magic. If you spend 48 hours over a period of 6 days or fewer studying the book\'s contents and practicing its guidelines, your Strength score increases by 2, as does your maximum for that score. The manual then loses its magic, but regains it in a century.',
        source: 'DMG'
    },
    'manual-of-golems': {
        name: 'Manual of Golems',
        type: 'wondrous-item',
        rarity: 'very-rare',
        weight: 5,
        cost: 'varies',
        costValue: 5000000,
        attunement: 'none',
        consumable: true,
        description: 'This tome contains information and incantations necessary to make a particular type of golem. The DM chooses the type or determines it randomly. To decipher and use the manual, you must be a spellcaster with at least two 5th-level spell slots. The book is consumed when the golem is completed. Clay Golem: 65,000 gp, 30 days. Flesh Golem: 50,000 gp, 60 days. Iron Golem: 100,000 gp, 120 days. Stone Golem: 80,000 gp, 90 days.',
        source: 'DMG'
    },
    'manual-of-quickness-of-action': {
        name: 'Manual of Quickness of Action',
        type: 'wondrous-item',
        rarity: 'very-rare',
        weight: 5,
        cost: '50,000 gp',
        costValue: 5000000,
        attunement: 'none',
        consumable: true,
        description: 'This book contains coordination and balance exercises, and its words are charged with magic. If you spend 48 hours over a period of 6 days or fewer studying the book\'s contents and practicing its guidelines, your Dexterity score increases by 2, as does your maximum for that score. The manual then loses its magic, but regains it in a century.',
        source: 'DMG'
    },
    'marvelous-pigments': {
        name: 'Marvelous Pigments',
        type: 'wondrous-item',
        rarity: 'very-rare',
        weight: 1,
        cost: '10,000 gp',
        costValue: 1000000,
        attunement: 'none',
        consumable: true,
        description: 'Typically found in 1d4 pots inside a fine wooden box with a brush (weighing 1 pound in total), these pigments allow you to create three-dimensional objects by painting them in two dimensions. The paint flows from the brush to form the desired object as you concentrate on its image. Each pot of paint is sufficient to cover 1,000 square feet of a surface, which lets you create inanimate objects or terrain features—such as a door, a pit, flowers, trees, cells, rooms, or weapons—that are up to 10,000 cubic feet. It takes 10 minutes to cover 100 square feet.',
        source: 'DMG'
    },
    'medallion-of-thoughts': {
        name: 'Medallion of Thoughts',
        type: 'wondrous-item',
        rarity: 'uncommon',
        weight: 0,
        cost: '1,000 gp',
        costValue: 100000,
        attunement: 'any',
        charges: 3,
        recharge: '1d3 at dawn',
        description: 'The medallion has 3 charges. While wearing it, you can use an action and expend 1 charge to cast the Detect Thoughts spell (save DC 13) from it. The medallion regains 1d3 expended charges daily at dawn.',
        source: 'DMG'
    },
    'mirror-of-life-trapping': {
        name: 'Mirror of Life Trapping',
        type: 'wondrous-item',
        rarity: 'very-rare',
        weight: 50,
        cost: '25,000 gp',
        costValue: 2500000,
        attunement: 'none',
        description: 'When this 4-foot-tall mirror is viewed indirectly, its surface shows faint images of creatures. The mirror weighs 50 pounds. It can be hung or placed on a surface and then activated by speaking its command word. It remains activated until you use an action to speak the command word again. Any creature other than you that sees its reflection in the activated mirror while within 30 feet of it must succeed on a DC 15 Charisma saving throw or be trapped, along with anything it is wearing or carrying, in one of the mirror\'s twelve extradimensional cells.',
        source: 'DMG'
    },
    'mithral-armor': {
        name: 'Mithral Armor',
        type: 'armor',
        subtype: 'any medium or heavy',
        rarity: 'uncommon',
        weight: 'varies (lighter)',
        cost: '800 gp',
        costValue: 80000,
        attunement: 'none',
        description: 'Mithral is a light, flexible metal. A mithral chain shirt or breastplate can be worn under normal clothes. If the armor normally imposes disadvantage on Dexterity (Stealth) checks or has a Strength requirement, the mithral version of the armor doesn\'t.',
        source: 'DMG'
    },
    'moonblade': {
        name: 'Moonblade',
        type: 'weapon',
        weaponType: 'martial',
        subtype: 'longsword',
        rarity: 'legendary',
        weight: 3,
        cost: '100,000 gp',
        costValue: 10000000,
        attunement: 'elf or half-elf of neutral good alignment',
        damage: '1d8',
        damageType: 'slashing',
        properties: ['finesse', 'versatile (1d10)', 'sentient'],
        description: 'Of all the magic items created by the elves, one of the most prized and jealously guarded is a moonblade. In ancient times, nearly all combative elven noble houses warded their bloodlines with these sentient, semi-divine blades. Over time, some blades gained the ability to evolve with their wielder through the generations, taking on additional magical properties to meet the challenges facing each new owner. A moonblade has one rune on its blade for each master it has served. A moonblade won\'t serve anyone it regards as craven, erratic, corrupt, or at odds with preserving and protecting elvenkind.',
        source: 'DMG'
    }
};
